CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  app_id CHAR(36) NOT NULL,
  client_order_id VARCHAR(191) NOT NULL,
  attempt_count INT NOT NULL DEFAULT 1,
  chapa_tx_ref VARCHAR(191) NOT NULL,
  chapa_reference VARCHAR(191) NULL,
  checkout_url VARCHAR(1024) NULL,
  status ENUM(
    'PENDING_CREATION',
    'FORWARDING',
    'RECOVERING',
    'INITIALIZED',
    'PAID',
    'FAILED',
    'SUPERSEDED',
    'SUPERSEDED_ORPHANED_ON_GATEWAY',
    'ABORTED'
  ) NOT NULL DEFAULT 'PENDING_CREATION',
  amount DECIMAL(18,2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'ETB',
  customer_email VARCHAR(255) NULL,
  return_url VARCHAR(1024) NULL,
  claimed_at DATETIME NULL,
  error_detail JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_txn_app FOREIGN KEY (app_id) REFERENCES applications(id) ON DELETE CASCADE,
  UNIQUE KEY uniq_app_order_attempt (app_id, client_order_id, attempt_count),
  UNIQUE KEY uniq_chapa_tx_ref (chapa_tx_ref),
  INDEX idx_txn_status_created (status, created_at),
  INDEX idx_txn_status_claimed (status, claimed_at),
  INDEX idx_txn_app_order (app_id, client_order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
