CREATE TABLE IF NOT EXISTS incoming_webhooks (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  event_ref VARCHAR(191) NOT NULL,
  payload JSON NOT NULL,
  status ENUM('RECEIVED', 'PROCESSED', 'DISCARDED') NOT NULL DEFAULT 'RECEIVED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at DATETIME NULL,
  UNIQUE KEY uniq_event_ref (event_ref)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
