CREATE TABLE IF NOT EXISTS system_status (
  id TINYINT NOT NULL PRIMARY KEY DEFAULT 1,
  chapa_status ENUM('OPERATIONAL', 'DEGRADED', 'PROBING') NOT NULL DEFAULT 'OPERATIONAL',
  last_failure_at DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO system_status (id, chapa_status) VALUES (1, 'OPERATIONAL')
ON DUPLICATE KEY UPDATE id = id;
